# Generated by Django 3.2.17 on 2023-10-11 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0005_auto_20231011_1827'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveField(
            model_name='event',
            name='time',
        ),
    ]
