# Generated by Django 3.2.17 on 2023-10-11 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0006_auto_20231011_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='access_coupons',
            field=models.ManyToManyField(blank=True, related_name='participants', to='corecode.AccessCoupon'),
        ),
    ]
