# Generated by Django 3.2.17 on 2023-10-11 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0007_participant_access_coupons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='access_coupons',
        ),
    ]
